### ISSUE TITLE
Add link/iframe to RDMO-software-milestones

### ISSUE THREAD

**Issue by Zack-83** [rdmorganiser/rdmorganiser.github.io#58]
The page https://github.com/rdmorganiser/rdmo/milestones hould appear in the website.

Part of #52

**Comment by triole** [comment]
Embedding an iframe does not seem to be a valid option. It is restricted due to cross origin access policy and wouldn't work. I would suggest to use the github api to fetch the date and render them into our webpage. 

Here is a first draft which is an outline of what I would do

https://github.com/rdmorganiser/rdmorganiser.github.io/tree/roadmap

**Comment by jochenklar** [comment]
Make sense, can you make a PR, then we can see the changes better. Does it work if you are not logged in to GitHub, i.e. is the API truly public?

**Comment by triole** [comment]
We may need some additional text if we put the roadmap on a distinct page. It looks a little empty.

![roadmap](https://github.com/rdmorganiser/rdmorganiser.github.io/assets/11279151/77766f90-cc7d-487d-86fc-a9163470b4b9)

@jochenklar yes, the api is truly public. however there is an excess limit which we have to consider. It may cause problems but I am not sure. Github says

```
The primary rate limit for unauthenticated requests is 60 requests per hour.
```

**Comment by jochenklar** [comment]
We could be happy if we get 60 requests a week... Überschrift vll besser: Weiterentwicklung, Text maybe:

> Die Weiterentwicklung von RDMO erfolgt anhand einer von der RDMO Community beschlossenen Roadmap. Die einzelnen Releases werden über [Milestones]() und [Issues]() auf GitHub organisiert. Derzeit arbeiten wir an den folgenden Releases:
